### ISSUE TITLE
Search bar functionality

### ISSUE THREAD

**Issue by Clue355** [Kamala-Facts-Team/kamala_facts_2_frontend#25]
The search bar should store the query in state and filter through the myths from the api
- [ ] store search query in state
- [ ] filter myths from api

![kamala3](https://user-images.githubusercontent.com/54788134/131268706-3d113991-9ead-4160-ae59-25fdfb69dfee.png)

**Comment by malasia-415** [comment]
Carlos built main page search functionality. 

**Navbar search functionality still in progress
